[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "invoice-summarizer"
version = "0.1.0"
description = "Automates the extraction of PDF invoices from Gmail and merges them."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "loguru",
    "PyPDF2",
]

[project.scripts]
invoice-summarizer = "src.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src"]
