name: Build
on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Build Docker Image
      uses: docker/build-push-action@v7.0.0 
      with:
        context: .
        push: false
