name: CRON EXECUTOR
on: 
  schedule: 
    - cron: "0 0 25 * *"
  workflow_dispatch:
jobs: 
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  
          ref: "main"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          load: true
          tags: invoice-summarizer:latest
      - name: Run Docker container
        run: make docker-run
        env: 
          EMAIL: ${{ secrets.EMAIL_ADDRESS }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
