name: pr-build
on: [pull_request]
jobs:
  handle-pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.0.0 
      - name: Docker BUILD
        uses: docker/build-push-action@v7.1.0
        with: 
          context: .
          file: "Dockerfile"
          platforms: linux/amd64
          push: false
